# Generated by Django 4.2.7 on 2023-12-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetowebapi',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
