# Generated by Django 4.2.7 on 2023-12-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projetowebapi_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetowebapi',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
