# Generated by Django 4.2.7 on 2023-12-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_projetowebapi_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=300)),
                ('imagem', models.CharField(max_length=150)),
            ],
        ),
    ]
