# Generated by Django 4.2.7 on 2024-02-09 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projetomobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoautomacao',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='projetomobile',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='projetowebapi',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
