# Generated by Django 4.2.7 on 2024-02-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projetoautomacao_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetowebapi',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
